### ISSUE TITLE
articleList null Why??

### ISSUE THREAD

**Issue by GerhardPue** [Pkmmte/PkRSS#11]
private static final String RSS_URL = "http://techdissected.com/category/google/feed/";

PkRSS.with(this).load(RSS_URL).async();

List< Article > articleList = PkRSS.with(this).get(RSS_URL);

articleList every time null ??? Why??

**Comment by Pkmmte** [comment]
Looks like you're loading the feed in the background first and trying to get the results before it finishes loading.

Either try replacing .async() with .sync() or use a callback with .callback(this) to be notified when it finishes loading.

**Comment by GerhardPue** [comment]
.sync() didn't exist! and .callback(this) gets a error like " callback (com.pkmmte.pkrss.Callback) in RequestCreater cannot be applied to (com.app.myapp.RssService)

code :  PkRSS.with(this).load(RSS_URL).callback(this).async();

**Comment by Pkmmte** [comment]
I see you're not familiar with interfaces. When you pass "this" as your callback, it implies that your class implements the necessary interface (in this case, com.pkmmte.pkrss.callback). 

If you're using Android Studio, pressing Alt + Enter with the error selected will bring up an option to automatically implement the interface for you. If you'd like shorter code, you can do it like this:

.callback(new Callback() {
    // Overriden stuff here
})

**Comment by GerhardPue** [comment]
Sorry ... I think I have importet  com.pkmmte.pkrss.callback ... but I havend .... sorry ... now it works..

One Question ......Is the whole List stored in DB and how long.....? because I have a feed whats changes very fast, but i need the Items longer....
