### ISSUE TITLE
.clearCache() didnt work!

### ISSUE THREAD

**Issue by GerhardPue** [Pkmmte/PkRSS#15]
I load the URL in a Service: 

// ClearCache
PkRSS.with(RssService.this).clearCache();

// Load URL
PkRSS.with(RssService.this).load(Constants.RSS_URL).parser(new Rss3Parser()).downloader(new OkHttpDownloader(RssService.this)).callback(RssService.this).async();

and get PKRSS Logcat

09-05 11:39:35.873  20848-20848/com.fanapp D/PkRSS﹕ Logging is now enabled
09-05 11:39:36.337  20848-20881/com.fanapp D/PkRSS﹕ New size for http://m.com/xml/rss is 20
09-05 11:39:36.645  20848-20894/com.fanapp D/PkRSS﹕ New size for http://m.com/xml/rss is 40
09-05 11:40:08.621  20848-21132/com.fanapp D/PkRSS﹕ New size for http://m.com/xml/rss is 60
09-05 11:41:48.721  20848-20863/com.fanapp D/PkRSS﹕ New size for http://m.com/xml/rss is 80

Why grows the Cache every time?

**Comment by GerhardPue** [comment]
so now I have my own DefaultDownloader ... with new cacheAge = 60 .. this solved my problem with the stored Cache // I add a Log at ClearCache in My Downloader .... this is never been called ?? Why??
this should  not be the right way or? 

and I clear the list bevor i load the  URL 

 List<Article> list = PkRSS.with(RssService.this).get(Constants.RSS_URL);

            if (list != null){
                list.clear();
                PkRSS.with(RssService.this).clearCache();
            }

//Load_URL

**Comment by Pkmmte** [comment]
The problem here is that you're making a new OkHttpDownloader instance every time you make a request. If you plan on using a custom Downloader for all requests, I suggest creating a custom PkRSS instance via the Builder and set it as the singleton via PkRSS.setSingleton().

As for the growing size, that's a bug even though the actual cache remains the same size. I'll get to fixing that.

**Comment by GerhardPue** [comment]
if i use this ...

  new PkRSS.Builder(this).parser(new Rss3Parser()).buildSingleton(); with or without .downloader()

I get:

D/PkRSS﹕ Logging is now enabled
E/PkRSS﹕ Cannot  buildSingleton(), a singleton already exists! Ignoring request...
D/PkRSS﹕ Replaced global singleton instance.
E/PkRSS﹕ Cannot buildSingleton(), a singleton already exists! Ignoring request... 

and Rss3Parser will never been used! 
mhmmmm

**Comment by Pkmmte** [comment]
Yeah, I'll admit that wasn't the best way of creating new singletons which is why I removed that and replaced it with .setSingleton() in version 1.2.

It should still work on that version if you replace "buildSingleton()" with "replace singleton()".

**Comment by GerhardPue** [comment]
If i want get the lastet .jar on your Website ... 

404 - Not Found

Path /com/pkmmte/pkrss/pkrss/1.2/pkrss-1.2.jar not found in local nor in remote storage of M2Repository(id=central-proxy)

**Comment by Pkmmte** [comment]
Try using the .aar file instead of a .jar. If your IDE does not support .aar libraries, you can fork and import the project instead.
