### ISSUE TITLE
Not compatible with Retrofit 2

### ISSUE THREAD

**Issue by markuskallander** [Pkmmte/PkRSS#31]
Hi,

I get this message when I use PkRSS in the same project as Retrofit 2 (http://square.github.io/retrofit/). Retrofit 2 uses okhttp 3.

java.lang.RuntimeException: PkRSS detected an unsupported OkHttp on the classpath.

Thanks
Markus

**Comment by magillus** [comment]
not compatible with OkHttp 3.0 different package name

**Comment by javmarina** [comment]
This is something that can be done. Just renaming packages and changing dependencies means a big benefit for developers who use this library. With some minutes of work from the developer, you can now be using the latest OkHttp release, with all its performance improvements, security additions and fixes. Remember that OkHttp 2.x is deprecated. I hope Pkmmte works soon on this!

**Comment by amardeshbd** [comment]
The exception comes from https://github.com/Pkmmte/PkRSS/blob/master/pkrss/src/main/java/com/pkmmte/pkrss/Utils.java#L49

So, i think it should be as simple as updating the package name in the `Class.forName()`

Also, if you look at https://github.com/Pkmmte/PkRSS/blob/master/pkrss/build.gradle#L16

It uses both v2 and v3 of **OkHttp**

```
  compile group: 'com.squareup.okhttp', name: 'okhttp', version: '2.5.0'
  compile group: 'com.squareup.okhttp3', name: 'okhttp', version: '3.2.0'
  compile group: 'com.squareup.okhttp', name: 'okhttp-urlconnection', version: '2.5.0'
```

**Comment by amardeshbd** [comment]
🤔  looks like @Pkmmte already has [OkHttp3Downloader](https://github.com/Pkmmte/PkRSS/blob/master/pkrss/src/main/java/com/pkmmte/pkrss/downloader/OkHttp3Downloader.java)

So, the fix would be simply updating the `Utils#createDefaultDownloader()` method.

```java

/**
 * Creates a Downloader object depending on the dependencies present.
 *
 * @param context Application context.
 * @return {@link com.pkmmte.pkrss.downloader.OkHttp3Downloader} if the OkHttp library is present, {@link DefaultDownloader} if not.
 */
public static Downloader createDefaultDownloader(Context context) {
	Downloader downloaderInstance = null;

	boolean okUrlFactory = false;
	try {
		Class.forName("com.squareup.okhttp.OkUrlFactory");
		okUrlFactory = true;
		downloaderInstance = new DefaultDownloader(context);
	} catch (ClassNotFoundException ignored) {}

	boolean okHttpClient = false;
	try {
		Class.forName("com.squareup.okhttp.OkHttpClient");
		okHttpClient = true;
		downloaderInstance = new OkHttpDownloader(context);
	} catch (ClassNotFoundException ignored) {}


	boolean okHttp3Client = false;
	try {
		Class.forName("okhttp3.OkHttpClient");
		okHttp3Client = true;
		downloaderInstance = new OkHttp3Downloader(context);
	} catch (ClassNotFoundException ignored) {}



	if (!okHttpClient && !okHttp3Client && !okUrlFactory) {
		throw new RuntimeException(""
									   + "PkRSS detected an unsupported OkHttp on the classpath.\n"
									   + "To use OkHttp with this version of PkRSS, you'll need:\n"
									   + "1. com.squareup.okhttp:okhttp:1.6.0 (or newer)\n"
									   + "2. com.squareup.okhttp:okhttp-urlconnection:1.6.0 (or newer)\n"
									   + "Note that OkHttp 2.0.0+ is supported!");
	}

	Log.d(TAG, "Downloader is " + downloaderInstance);
	return okHttpClient ? new OkHttp3Downloader(context) : new DefaultDownloader(context);
}
```

**Comment by Pkmmte** [comment]
Hey everyone! Sorry for not being so active lately.

@amardeshbd I saw you've already created a pull request for this. I'll review it shortly and merge it. Thanks!
