### ISSUE TITLE
Special characters in Spanish

### ISSUE THREAD

**Issue by edgarmacas** [Pkmmte/PkRSS#4]
Greetings .. please help .. when the library does not implement special characters are shown and displayed in unicode, but when I put it on TechDissected url displays correctly, that thing is making me missing you ..

**Comment by Maragues** [comment]
@edgarmacas could you ellaborate on how you solved it?

**Comment by Pkmmte** [comment]
@Maragues has fixed this issue in commit https://github.com/Maragues/PkRSS/commit/b216127c077b29e280ec7c7970dd5b6a1ffd35c0 so I'll be closing this issue now. Feel free to reopen it if the issue persists.

**Comment by edgarmacas** [comment]
apologize for not answering soon.. I solved my problem by importing
the libraries: repackaged-okhttp-2.0.0.jar,
repackaged-okhttp-urlconnection-2.0.0.jar and
repackaged-okio-1.0.0.jar


2015-07-19 2:33 GMT-05:00 Pkmmte Xeleon <notifications@github.com>:
