### ISSUE TITLE
Callback thread and reference

### ISSUE THREAD

**Issue by vincentbrison** [Pkmmte/PkRSS#5]
Hi,
This library looks really promising !

But as you mentioned in this commit : https://github.com/Pkmmte/TechDissected/commit/47da228f035704b8c3bd543e411a5ee78be33eb3
it would be great if callback are called by default on the main thread. It looks very disturbing from the controller point of view to set a callback, call async, and get the result on a thread it did not create at all. I saw you implemented this on an 1.1.3 snapshot, is there any chance to get this release through maven ?

By the way, it would be also great to hold only weak references on callbacks, since we obviously do not want any fragment or activity held by the downloader and parser threads of your library.

**Comment by esoxjem** [comment]
Any update on this? Callback should be on the main thread. Or the API could ask for the thread where callbacks should happen.

**Comment by Pkmmte** [comment]
The commits to improve this have been pushed. I'll deploy an update to Maven once I find my key...

**Comment by esoxjem** [comment]
Is this on Gradle yet? :)

**Comment by Pkmmte** [comment]
Yup!
Version 1.2 has been released a couple days ago on Maven.
